import { PageHeader } from "@/components/PageHeader";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { ResetAnalyticsButton } from "@/components/ResetAnalyticsButton";

export default async function AnalyticsPage({ searchParams }: { searchParams: Promise<{ range?: string; status?: string; targetType?: string; website?: string; resetError?: string; resetMessage?: string }> }) {
  const user = await requireUser();
  const filters = await searchParams;
  const days = filters.range === "all" ? null : Number(filters.range || 30);
  // Server-side analytics intentionally use the current request time as the range boundary.
  // eslint-disable-next-line react-hooks/purity
  const createdAt = days ? { gte: new Date(Date.now() - days * 86400000) } : undefined;
  const rows = await prisma.automationTransaction.findMany({ where: { userId: user.id, createdAt, status: filters.status || undefined, targetType: filters.targetType || undefined, websiteUrl: filters.website ? { contains: filters.website } : undefined }, orderBy: { createdAt: "desc" } });
  const total = rows.length;
  const success = rows.filter((row) => ["success", "dry_run_ready_to_book"].includes(row.status)).length;
  const failed = rows.filter((row) => row.status === "failed").length;
  const live = rows.filter((row) => row.liveSubmit).length;
  const statusCounts = countBy(rows.map((row) => row.status));
  const typeCounts = countBy(rows.map((row) => row.targetType || "unknown"));
  const dayCounts = countBy(rows.map((row) => row.createdAt.toISOString().slice(0, 10)));
  const maxDay = Math.max(1, ...Object.values(dayCounts));
  return <><PageHeader title="Analytics" description="Filter and analyze every automation transaction, target type, success outcome and website." />
    <form className="mb-6 grid gap-3 rounded-2xl border border-line bg-white p-4 shadow-soft md:grid-cols-6"><select className="rounded-xl border border-line p-2.5" defaultValue={filters.range || "30"} name="range"><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="all">All time</option></select><select className="rounded-xl border border-line p-2.5" defaultValue={filters.status || ""} name="status"><option value="">All statuses</option>{Object.keys(statusCounts).map((x) => <option key={x}>{x}</option>)}</select><select className="rounded-xl border border-line p-2.5" defaultValue={filters.targetType || ""} name="targetType"><option value="">All target types</option>{Object.keys(typeCounts).map((x) => <option key={x}>{x}</option>)}</select><input className="rounded-xl border border-line p-2.5" defaultValue={filters.website} name="website" placeholder="Filter website" /><button className="rounded-xl bg-brand px-4 py-2 font-semibold text-white">Apply filters</button><a className="rounded-xl border border-line bg-white px-4 py-2 text-center font-semibold text-brand" href="/analytics">Reset filters</a></form>
    <div className="grid gap-4 md:grid-cols-4">{[["Transactions",total],["Successful",success],["Failed",failed],["Live submissions",live]].map(([label,value]) => <div className="rounded-2xl border border-line bg-white p-5 shadow-soft" key={label}><p className="text-xs font-semibold uppercase tracking-wide text-muted">{label}</p><p className="mt-2 text-3xl font-bold text-ink">{value}</p></div>)}</div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><Chart title="Transactions by day">{Object.entries(dayCounts).sort().map(([label,value]) => <div className="flex items-end gap-3" key={label}><span className="w-24 text-xs text-muted">{label.slice(5)}</span><div className="h-7 rounded-r-lg bg-gradient-to-r from-brand to-cyan-400" style={{width:`${Math.max(4,value/maxDay*75)}%`}} /><b className="text-sm">{value}</b></div>)}</Chart><Chart title="Status distribution"><Bars data={statusCounts} /></Chart><Chart title="Target type breakdown"><Bars data={typeCounts} /></Chart><Chart title="Success rate"><div className="flex min-h-48 items-center justify-center"><div className="flex h-40 w-40 items-center justify-center rounded-full" style={{background:`conic-gradient(#10b981 ${total ? success/total*360 : 0}deg,#e2e8f0 0)`}}><div className="flex h-28 w-28 flex-col items-center justify-center rounded-full bg-white"><b className="text-3xl">{total ? Math.round(success/total*100) : 0}%</b><span className="text-xs text-muted">successful</span></div></div></div></Chart></div>
    <div className="mt-6 overflow-hidden rounded-2xl border border-line bg-white shadow-soft"><div className="border-b border-line p-5"><h2 className="font-bold">Recent transactions</h2></div><div className="max-h-96 overflow-auto"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-canvas text-xs uppercase text-muted"><tr><th className="p-3">Time</th><th className="p-3">Website</th><th className="p-3">Target</th><th className="p-3">Status</th><th className="p-3">Mode</th></tr></thead><tbody>{rows.slice(0,100).map((row) => <tr className="border-t border-line" key={row.id}><td className="p-3">{row.createdAt.toLocaleString()}</td><td className="max-w-xs break-all p-3">{row.websiteUrl}</td><td className="p-3">{row.targetType || "-"}</td><td className="p-3 font-semibold">{row.status}</td><td className="p-3">{row.liveSubmit ? "Live" : "Dry"}</td></tr>)}</tbody></table></div></div>
    <section className="mt-6 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-red-200 bg-red-50 p-5 shadow-soft"><div><h2 className="font-bold text-red-900">Reset analytics data</h2><p className="mt-1 text-sm text-red-700">Permanently deletes every stored analytics transaction.</p></div><ResetAnalyticsButton error={filters.resetError} message={filters.resetMessage} /></section>
  </>;
}
function countBy(values: string[]) { return values.reduce<Record<string,number>>((out,value) => { out[value]=(out[value]||0)+1; return out; },{}); }
function Chart({title,children}:{title:string;children:React.ReactNode}) { return <section className="rounded-2xl border border-line bg-white p-5 shadow-soft"><h2 className="mb-5 font-bold">{title}</h2><div className="space-y-3">{children}</div></section>; }
function Bars({data}:{data:Record<string,number>}) { const max=Math.max(1,...Object.values(data)); return <>{Object.entries(data).sort((a,b)=>b[1]-a[1]).map(([label,value])=><div className="grid grid-cols-[130px_1fr_35px] items-center gap-2" key={label}><span className="truncate text-xs text-muted">{label}</span><div className="h-7 overflow-hidden rounded-lg bg-slate-100"><div className="h-full rounded-lg bg-gradient-to-r from-indigo-500 to-cyan-400" style={{width:`${value/max*100}%`}} /></div><b className="text-sm">{value}</b></div>)}</>; }
